### ISSUE TITLE
Error downloading the template

### ISSUE THREAD

**Issue by tarastclair** [Azure/azure-quickstart-templates#8288]
[Azure Quickstart](https://github.com/Azure/azure-quickstart-templates/blob/master/sas-viya/azuredeploy.json)

### Issue Details
Automatically redirected to an error when attempting to deploy (was not happening last week). Error is:

_There was an error downloading the template from URI 'https://github.com/Azure/azure-quickstart-templates/blob/master/sas-viya/azuredeploy.json'. Ensure that the template is publicly accessible and that the publisher has enabled CORS policy on the endpoint. To deploy this template, download the template manually and paste the contents in the 'Build your own template in the editor' option below._ 

### Repro steps
1. Navigate to [https://azure.microsoft.com/en-us/resources/templates/sas-viya/](https://azure.microsoft.com/en-us/resources/templates/sas-viya/) then click the "Deploy to Azure" button

**Comment by tarastclair** [comment]
Interestingly, we just found that if you refresh the page after being redirected to the error as described, you will be presented with another screen with a "Select a template" tab. There is a dropdown on that page and if you search for "sas" you will see "sas-viya" ... if you select that template you will be presented with the list of parameters as expected.

**Comment by Yvand** [comment]
I also get this error since today, and it probably affects all templates.
It's caused by the format of query string in "Deploy to Azure" button: Currently query string uses this format:
https://github.com/Azure/azure-quickstart-templates/blob/master/sharepoint-adfs/azuredeploy.json
But somehow now GitHub seems to require this format:
https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/sharepoint-adfs/azuredeploy.json

It's possible there is an issue on GitHub side though

**Comment by andybouts** [comment]
I agree, I documented in my notes that it should always be this (at least until something changes and it’s not): 
https://raw.githubusercontent.com/azure/azure-quickstart-templates/master/sas-viya/azuredeploy.json

**Comment by andybouts** [comment]
Hey @Yvand  and @tarastclai, this seems to be working as expected now.

**Comment by Yvand** [comment]
Nope, I just tested and I keep getting the error on all the templates (I tested 4 randomly).

**Comment by andybouts** [comment]
﻿Yep, it’s not working for me today, but it worked yesterday.  That’s really unfortunate.

--
Andy Bouts, PMP, M.Sc.
980-938-1827 (O)
704-454-8806 (M)
andy.bouts@sas.com<mailto:andy.bouts@sas.com>

**Comment by bmoore-msft** [comment]
ACOM had a bug - I think it's been fixed now

**Comment by andybouts** [comment]
I tried it 3 times and it worked as expected.  Thanks for the fix.

--
Andy Bouts, PMP, M.Sc.

**Comment by bmoore-msft** [comment]
Thanks for confirming...

**Comment by DeanGross** [comment]
I am getting this error. The fix seems to have failed

**Comment by hardikhari96** [comment]
> ACOM had a bug - I think it's been fixed now

Currently  I faced this same issue, 

My steps 

1. visited https://hub.docker.com/editions/community/docker-ce-azure
2. clicked on azure container template
3. seen too many redirects 
4. **after many redirect I landed on azure page where I got this error**
5. after I refreshed the page,  I got template 😊 means issue is still there
